#!/bin/sh
if test "x${NRNHOME}" = "x" ; then
	NRNHOME="/home/jbhunt/neuron/nrn-7.6"
fi
if test "x${NRNBIN}" = "x" ; then
	NRNBIN="/home/jbhunt/neuron/nrn-7.6/x86_64/bin/"
fi
if test "" = "yes" ; then
	NRNIV="${NRNBIN}nrniv.app/Contents/MacOS/nrniv"
else
	NRNIV="${NRNBIN}nrniv"
fi
"${NRNIV}" -dll "/home/jbhunt/Dropbox/Code/Python/lib/sacnet/sacnet/data/mechanisms/x86_64/.libs/libnrnmech.so" "$@"
