# Sampling rates (in Hz)
SAMPLING_RATE_LABJACK     = 2000
SAMPLING_RATE_CAMERAS     = 200
SAMPLING_RATE_BLACKFLYS   = 1000000000
SAMPLING_RATE_NEUROPIXELS = 30000

# Direction of monocular saccades
MONOCULAR_SACCADE_DIRECTION_FALSE    = 0
MONOCULAR_SACCADE_DIRECTION_NASAL    = 1
MONOCULAR_SACCADE_DIRECTION_TEMPORAL = 2

# Direction of conjugate saccades
CONJUGATE_SACCADE_DIRECTION_DIVERGENT    = 1
CONJUGATE_SACCADE_DIRECTION_CONVERGENT   = 2
CONJUGATE_SACCADE_DIRECTION_IPSILATERAL  = 3
CONJUGATE_SACCADE_DIRECTION_CONTALATERAL = 4

# Code for target events
TARGET_EVENT_STOP    = 0
TARGET_EVENT_PROBE   = 1
TARGET_EVENT_MOTION  = 2
TARGET_EVENT_GRATING = 3
TARGET_EVENT_SACCADE = 4

# Code for probe contrast level
PROBE_CONTRAST_LOW    = 1
PROBE_CONTRAST_MEDIUM = 2
PROBE_CONTRAST_HIGH   = 3
